version: '3'

services:
  springboot-app:
    container_name: 'app'
    image: 'docker-spring-boot-mysql:latest'
    build: .
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: Pa$$w0rd
      MYSQL_PORT: 3305
  db:
    container_name: db
    image: mysql
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: Hospital
      MYSQL_ROOT_PASSWORD: Pa$$w0rd

