version: '2'

services:
  app:
    image: 'docker-spring-boot-mysql:latest'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/Hospital
      - spring.datasource.username=root
      - spring.datasource.password=Pa$$w0rd
      - spring.jpa.hibernate.ddl-auto=update

  db:
    image: 'mysql'
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=Pa$$w0rd