version: '2'

services:
  app:
    image: 'docker-spring-boot-mysql:latest'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:5432/Hospital
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pa$$w0rd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: Hospital
